import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";
import { AppProvider } from "@/components/AppContext";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AppProvider>
            <Header />
            {children}
            <footer className=" border-t text-center py-8 mt-16">
              <p className="text-gray-500">
                &copy; {new Date().getFullYear()} Pizza Place - all rights
                reserved
              </p>
            </footer>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
