name: Mikrus T395 CI/CD (manual trigger)

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE_NAME: e-commerce-pizza

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE_NAME }}:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag ${{ env.DOCKER_IMAGE_NAME }}:latest ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and execute commands
        uses: appleboy/ssh-action@master
        with:
          host: srv22.mikr.us
          username: root
          key: ${{ secrets.MIKRUS_T395_PRIVATE_KEY }}
          port: 10395
          script: |
            CONTAINER_ID=$(docker ps -aq --filter "ancestor=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }}") &&
            [ -n "$CONTAINER_ID" ] &&
            echo "Container ID to remove: $CONTAINER_ID" &&
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }} &&
            docker rm -f $CONTAINER_ID &&
            docker run -p 20395:3000 -e MONGODB_URL=${{ secrets.MIKRUS_T395_MONGO_DB_URL }} -e NEXTAUTH_URL=${{ secrets.MIKRUS_T395_NEXTAUTH_URL }} -e NEXTAUTH_SECRET=${{ secrets.MIKRUS_T395_NEXTAUTH_SECRET }} -e GOOGLE_CLIENT_ID=${{ secrets.MIKRUS_T395_GOOGLE_CLIENT_ID }} -e GOOGLE_CLIENT_SECRET=${{ secrets.MIKRUS_T395_GOOGLE_CLIENT_SECRET }} -e AWS_ACCESS_KEY_ID=${{secrets.AWS_ACCESS_KEY_ID}} -e AWS_SECRET_ACCESS_KEY=${{secrets.AWS_SECRET_ACCESS_KEY}} -d ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKER_IMAGE_NAME }} &&
            docker image prune -f
