name: Deploy Next.js App to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Send .next folder to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: .next
          target: ${{ vars.DOMAIN_PATH }}/adm-e-commerce

      - name: Restart site on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ vars.DOMAIN_PATH }}/adm-e-commerce && git pull && npm ci && devil www restart e-commerce.sandbox.usermd.net

    #   - name: Install dependencies and build
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SERVER_HOST }}
    #       username: ${{ secrets.SERVER_USERNAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: |
    #         ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd ${{ vars.DOMAIN_PATH}} && npm ci && npm run build"

    #   - name: Restart site on server
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SERVER_HOST }}
    #       username: ${{ secrets.SERVER_USERNAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: |
    #         ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "devil www restart e-commerce.sandbox.usermd.net"
