name: Deploy Next.js App to Server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: test read form repo
        run: |

          echo ${{ vars.DOMAIN_PATH}}

    #   - name: Setup Node.js
    #     uses: actions/setup-node@v2
    #     with:
    #       node-version: "18.17"

    #   - name: Install dependencies and build
    #     run: |
    #       npm install
    #       npm run build

    #   - name: Create folder with current date on server
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SERVER_HOST }}
    #       username: ${{ secrets.SERVER_USERNAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: |
    #         CURRENT_DATE=$(date +"%Y-%m-%d")
    #         ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "mkdir -p $CURRENT_DATE"

    #   - name: Deploy to Server under current date folder
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SERVER_HOST }}
    #       username: ${{ secrets.SERVER_USERNAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: |
    #         CURRENT_DATE=$(date +"%Y-%m-%d")
    #         scp -r ./out/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:$CURRENT_DATE/

    #   - name: Execute command in the new folder on the server
    #     uses: appleboy/ssh-action@master
    #     with:
    #       host: ${{ secrets.SERVER_HOST }}
    #       username: ${{ secrets.SERVER_USERNAME }}
    #       key: ${{ secrets.SSH_PRIVATE_KEY }}
    #       script: |
    #         CURRENT_DATE=$(date +"%Y-%m-%d")
    #         ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "cd $CURRENT_DATE && echo 'done'"
